# Run ONCE on any machine that should run the Telegram bot.
#
#   powershell -ExecutionPolicy Bypass -File scripts\install_bot_autostart.ps1
#
# Generates a Startup-folder launcher pointing at THIS checkout's actual
# location (unlike the supervisor .ps1, a Startup .vbs can't find its own
# original folder after being copied out to shell:startup, so its path
# has to be baked in at install time, per machine).
#
# Safe to re-run - overwrites the existing entry rather than duplicating it.

$root = Split-Path $PSScriptRoot -Parent
$supervisor = Join-Path $PSScriptRoot "run_telegram_polling_forever.ps1"
$startupFolder = [Environment]::GetFolderPath("Startup")
$vbsPath = Join-Path $startupFolder "TalentLiveTelegramBot.vbs"

if (-not (Test-Path $supervisor)) {
    Write-Error "Could not find $supervisor - run this from inside the cloned repo."
    exit 1
}

$vbsContent = @"
' Launches the Telegram bot supervisor with no visible console window.
' Generated by install_bot_autostart.ps1 - do not hand-edit, re-run that
' script instead if this needs to change.
Set shell = CreateObject("WScript.Shell")
shell.Run "powershell.exe -WindowStyle Hidden -ExecutionPolicy Bypass -NoProfile -File ""$supervisor""", 0, False
"@

Set-Content -Path $vbsPath -Value $vbsContent -Encoding ASCII

Write-Host "Installed Startup entry: $vbsPath"
Write-Host "Points at supervisor: $supervisor"
Write-Host ""
Write-Host "Starting it now for this session too..."

Start-Process -FilePath "wscript.exe" -ArgumentList "`"$vbsPath`""

Start-Sleep -Seconds 3

$proc = Get-CimInstance Win32_Process -Filter "Name='python.exe'" |
    Where-Object { $_.CommandLine -match "app\.telegram_polling" }

if ($proc) {
    Write-Host "Confirmed running (PID $($proc.ProcessId))."
} else {
    Write-Host "Not detected running yet - check $root\telegram_polling.log"
}

Write-Host ""
Write-Host "It will now also start automatically every time this machine logs into Windows."
Write-Host "Make sure .env exists in $root with real values before relying on this - it's gitignored, so it doesn't come from git clone."
